---
- hosts: docker

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Running openrc && starting nginx server
      shell:
        openrc && \
        touch /run/openrc/softlevel && \
        rc-service nginx restart
      
    - name: Checking if ports work
      shell: netstat -tupln | grep :80
      register: com
      failed_when: '"not found" in com.stderr or com.stdout == ""'
 
    - name: Testing nginx config
      shell: nginx -t 
      register: test

    - name: Copying server config
      copy:
        src: /root/server.conf
        dest: /etc/nginx/http.d
    
    - name: Downloading iputils
      apk:
        name: iputils
        state: present

    - name: Getting IPs
      shell: ip addr show eth0 | grep "inet" | cut -d " " -f 6
      register: ips

    - name: Debugging IPs
      debug:
        msg: "{{ ips.stdout }}"

    - name: Check for default config
      stat: 
        path: /etc/nginx/http.d/default.conf.bak
      register: out

    - name: Make default obsoulete
      shell: mv default.conf default.conf.bak
      when: out.stat.exists

    - name: Changing default config
      shell: |
        mkdir -p /root/public
        chmod +x /root && chmod +x /root/public
        cd /root/public
        echo -e '<h1>Hello, This server is automatically generated</h1>\n<h2>From - "{{ ips.stdout }}"</h2>' > index.html


    # Turn this into a if-else thing
   #  mv default.conf default.conf.bak
    
