---
# tasks file for terraform

- import_role:
    name: global-vars

- name: "Terra Init"
  shell: |
    cd {{ dir }};
    terraform init;

- name: "Terra Plan"
  shell: |
    cd {{ dir }};
    terraform plan -out plan.tfplan -var 'num={{ number_of_slaves }}';
  register: plan

# - name: "Display output: Terra Plan"
#   debug:
#     msg: "{{ plan.stdout }}"

- name: "Terra Apply"
  shell: |
    cd {{ dir }};
    terraform apply "plan.tfplan";
  register: app

# - name: "Display output: Terra Apply"
#   debug:
#     msg: "{{ app }}"
