---
- hosts: localhost1
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
  roles:
    - terraform
    - doc_hosts

- hosts: master

  roles:
    - global-vars

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ping master
      action: ping

    - name: Init Anisble config
      shell: |
        cd /root
        ansible-config init --disabled > ansible.cfg
        sed -i "s/;enable_plugins/enable_plugins/g" ansible.cfg

    - name: Copying hosts file to master
      copy:
        src: "{{ home_dir }}/hosts.docker.txt"
        dest: /root/hosts.ini

    - name: Check if ping happens
      shell: |
        echo "$PATH"
        ansible docker -m ping -i hosts.ini
      register: out
    
    - name: output
      debug: 
        msg: "{{ out.stdout }}"

#    - name: "Getting Docker Info"

# Change the nginx contents to distinguish

# Send a GET request to the individual nginx conts and check it right (Or if they get thru at all)

